include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/l10n/gen/*.dart'
    - "lib/models/**.g.dart"
    - "lib/routes/juejin_route**.dart"

linter:
  rules:
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_slow_async_io: true
    avoid_void_async: true
    constant_identifier_names: false
    directives_ordering: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
