// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.9
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
import 'package:flutter/foundation.dart';
import 'package:juejin/exports.dart';

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'article-detail-page',
  'club-page',
  'home-page',
  'login-page',
  'splash-page',
  'user-profile',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'article-detail-page'
  ///
  /// [name] : 'article-detail-page'
  ///
  /// [constructors] :
  ///
  /// ArticleDetailPage : [String(required) id, Key? key, ArticleItemModel? item]
  static const _ArticleDetailPage articleDetailPage = _ArticleDetailPage();

  /// 'club-page'
  ///
  /// [name] : 'club-page'
  ///
  /// [constructors] :
  ///
  /// ClubPage : [String(required) id, Key? key, PinTopic? topic]
  static const _ClubPage clubPage = _ClubPage();

  /// 'home-page'
  ///
  /// [name] : 'home-page'
  ///
  /// [constructors] :
  ///
  /// HomePage : [Key? key]
  static const _HomePage homePage = _HomePage();

  /// 'login-page'
  ///
  /// [name] : 'login-page'
  ///
  /// [constructors] :
  ///
  /// LoginPage : [Key? key]
  static const _LoginPage loginPage = _LoginPage();

  /// 'splash-page'
  ///
  /// [name] : 'splash-page'
  ///
  /// [constructors] :
  ///
  /// SplashPage : [Key? key]
  static const _SplashPage splashPage = _SplashPage();

  /// 'user-profile'
  ///
  /// [name] : 'user-profile'
  static const _UserProfile userProfile = _UserProfile();
}

class _ArticleDetailPage {
  const _ArticleDetailPage();

  String get name => 'article-detail-page';

  Map<String, dynamic> d(
    String id, {
    Key? key,
    ArticleItemModel? item,
  }) =>
      <String, dynamic>{
        'id': id,
        'key': key,
        'item': item,
      };

  @override
  String toString() => name;
}

class _ClubPage {
  const _ClubPage();

  String get name => 'club-page';

  Map<String, dynamic> d(
    String id, {
    Key? key,
    PinTopic? topic,
  }) =>
      <String, dynamic>{
        'id': id,
        'key': key,
        'topic': topic,
      };

  @override
  String toString() => name;
}

class _HomePage {
  const _HomePage();

  String get name => 'home-page';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _LoginPage {
  const _LoginPage();

  String get name => 'login-page';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _SplashPage {
  const _SplashPage();

  String get name => 'splash-page';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _UserProfile {
  const _UserProfile();

  String get name => 'user-profile';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}
